## 시리즈 미니퀘스트 1번

In [1]:
import pandas as pd

series = pd.Series([5, 10, 15, 20])

print(series.index)

RangeIndex(start=0, stop=4, step=1)

## 시리즈 미니퀘스트 2번

In [2]:
import pandas as pd

data = {'a': 100, 'b': 200, 'c': 300}

series = pd.Series(data)

print(series['b'])

200

## 시리즈 미니퀘스트 3번

In [3]:
import pandas as pd

series = pd.Series([1, 2, None, 4, None, 6])

print(series.isna())

filled_series = series.fillna(0)

print(filled_series)

0    False
1    False
2     True
3    False
4     True
5    False
dtype: bool
0    1.0
1    2.0
2    0.0
3    4.0
4    0.0
5    6.0
dtype: float64

## 데이터프레임 미니퀘스트 1번

In [5]:
import pandas as pd

data = {'이름': ['홍길동', '김철수', '박영희'], 
        '나이': [25, 30, 28], 
        '성별': ['남', '남', '여']}
df = pd.DataFrame(data)

print(df.columns)

Index(['이름', '나이', '성별'], dtype='str')

## 데이터프레임 미니퀘스트 2번

In [6]:
import pandas as pd

data = {
    '이름': ['홍길동', '김철수', '박영희'],
    '나이': [25, 30, 28],
    '성별': ['남', '남', '여']
}

df = pd.DataFrame(data)

sorted_df = df.sort_values(by='나이')

print(sorted_df)

    이름  나이 성별
0  홍길동  25  남
2  박영희  28  여
1  김철수  30  남

## 데이터프레임 미니퀘스트 3번

In [7]:
import pandas as pd

data = {
    '이름': ['홍길동', '김철수', '박영희', '이순신'],
    '국어': [85, 90, 88, 92],
    '영어': [78, 85, 89, 87],
    '수학': [92, 88, 84, 90]
}

df = pd.DataFrame(data)

df['총점'] = df['국어'] + df['영어'] + df['수학']

result = df[df['총점'] >= 250]

print(result)

    이름  국어  영어  수학   총점
0  홍길동  85  78  92  255
1  김철수  90  85  88  263
2  박영희  88  89  84  261
3  이순신  92  87  90  269

## 필터링 미니퀘스트 1번

In [8]:
import pandas as pd

data = {
    '이름': ['홍길동', '김철수', '박영희', '이순신', '강감찬'],
    '나이': [25, 30, 35, 40, 45],
    '도시': ['서울', '부산', '서울', '대구', '부산']
}

df = pd.DataFrame(data)

result = df[df['나이'] >= 30]

print(result)

    이름  나이  도시
1  김철수  30  부산
2  박영희  35  서울
3  이순신  40  대구
4  강감찬  45  부산

## 필터링 미니퀘스트 2번

In [9]:
import pandas as pd

data = {
    '이름': ['홍길동', '김철수', '박영희', '이순신', '강감찬'],
    '나이': [25, 30, 35, 40, 45],
    '도시': ['서울', '부산', '서울', '대구', '부산'],
    '점수': [85, 90, 75, 95, 80]
}

df = pd.DataFrame(data)

result = df[(df['도시'] == '서울') | (df['점수'] >= 80)]

print(result)

    이름  나이  도시  점수
0  홍길동  25  서울  85
1  김철수  30  부산  90
2  박영희  35  서울  75
3  이순신  40  대구  95
4  강감찬  45  부산  80

## 필터링 미니퀘스트 3번

In [10]:
import pandas as pd

data = {
    '이름': ['홍길동', '김철수', '박영희', '이순신', '강감찬'],
    '나이': [25, 30, 35, 40, 45],
    '도시': ['서울', '부산', '서울', '대구', '부산'],
    '점수': [85, 90, 75, 95, 80]
}

df = pd.DataFrame(data)

result = df.query('나이 >= 35 and 점수 > 80')

print(result)

    이름  나이  도시  점수
3  이순신  40  대구  95

## 그룹화 미니퀘스트 1번

In [11]:
import pandas as pd

data = {
    '이름': ['홍길동', '김철수', '박영희', '이순신'],
    '부서': ['영업', '영업', '인사', '인사'],
    '급여': [5000, 5500, 4800, 5100]
}

df = pd.DataFrame(data)

result = df.groupby('부서')['급여'].sum()

print(result)

부서
영업    10500
인사     9900
Name: 급여, dtype: int64

## 그룹화 미니퀘스트 2번

In [12]:
import pandas as pd

data = {
    '이름': ['홍길동', '김철수', '박영희', '이순신', '강감찬', '신사임당'],
    '부서': ['영업', '영업', '인사', '인사', 'IT', 'IT'],
    '급여': [5000, 5500, 4800, 5100, 6000, 6200]
}

df = pd.DataFrame(data)

result = df.groupby('부서')['급여'].agg(['sum', 'mean'])

print(result)

      sum    mean
부서
IT  12200  6100.0
영업  10500  5250.0
인사   9900  4950.0

## 그룹화 미니퀘스트 3번

In [13]:
import pandas as pd

data = {
    '이름': ['홍길동', '김철수', '박영희', '이순신', '강감찬', '신사임당'],
    '부서': ['영업', '영업', '인사', '인사', 'IT', 'IT'],
    '급여': [5000, 5500, 4800, 5100, 6000, 6200]
}

df = pd.DataFrame(data)

result = df.groupby('부서')['급여'].mean()

filtered_result = result[result >= 5000]

print(filtered_result)

부서
IT    6100.0
영업    5250.0
Name: 급여, dtype: float64

## 미니퀘스트 병합 1번

In [14]:
import pandas as pd

df1 = pd.DataFrame({
    '고객ID': [1, 2, 3],
    '이름': ['홍길동', '김철수', '이영희']
})

df2 = pd.DataFrame({
    '고객ID': [2, 3, 4],
    '구매액': [1000, 2000, 3000]
})

result = pd.merge(df1, df2, on='고객ID', how='inner')

print(result)

   고객ID   이름   구매액
0     2  김철수  1000
1     3  이영희  2000

## 미니퀘스트 병합 2번

In [15]:
import pandas as pd

df1 = pd.DataFrame({
    '고객ID': [1, 2, 3],
    '이름': ['홍길동', '김철수', '이영희']
})

df2 = pd.DataFrame({
    '고객ID': [2, 3, 4],
    '구매액': [1500, 2500, 3500]
})

result = pd.merge(df1, df2, on='고객ID', how='left')

print(result)

   고객ID   이름     구매액
0     1  홍길동     NaN
1     2  김철수  1500.0
2     3  이영희  2500.0

## 미니퀘스트 병합 3번

In [16]:
import pandas as pd

df1 = pd.DataFrame({
    '고객ID': [1, 2, 3],
    '도시': ['서울', '부산', '대전'],
    '구매': [10000, 20000, 30000]
})

df2 = pd.DataFrame({
    '고객ID': [1, 2, 3],
    '도시': ['서울', '부산', '광주'],
    '구매': [15000, 25000, 35000]
})

result = pd.merge(
    df1,
    df2,
    on=['고객ID', '도시'],
    how='inner',
    suffixes=('_df1', '_df2')
)

print(result)

   고객ID  도시  구매_df1  구매_df2
0     1  서울   10000   15000
1     2  부산   20000   25000

## 결측치 미니퀘스트 1번

In [17]:
import pandas as pd
import numpy as np

data = {
    '이름': ['홍길동', '김철수', np.nan, '이영희'],
    '나이': [25, np.nan, 30, 28],
    '성별': ['남', '남', '여', np.nan]
}

df = pd.DataFrame(data)

print(df.isna().sum())

이름    1
나이    1
성별    1
dtype: int64

## 결측치 미니퀘스트 2번

In [18]:
import pandas as pd
import numpy as np

data = {
    '이름': ['홍길동', '김철수', np.nan, '이영희'],
    '나이': [25, np.nan, 30, 28],
    '성별': ['남', '남', '여', np.nan]
}

df = pd.DataFrame(data)

new_df = df.dropna()

print(new_df)

    이름    나이 성별
0  홍길동  25.0  남

## 결측치 미니퀘스트 3번

In [19]:
import pandas as pd
import numpy as np

data = {
    '이름': ['홍길동', '김철수', np.nan, '이영희'],
    '나이': [25, np.nan, 30, 28],
    '성별': ['남', '남', '여', np.nan]
}

df = pd.DataFrame(data)

new_df = df.copy()
new_df['나이'] = new_df['나이'].fillna(new_df['나이'].mean())

print(new_df)

    이름         나이   성별
0  홍길동  25.000000    남
1  김철수  27.666667    남
2  NaN  30.000000    여
3  이영희  28.000000  NaN

## 피벗 미니퀘스트 1번

In [20]:
import pandas as pd

data = {
    '날짜': ['2024-01-01', '2024-01-01', '2024-01-02', '2024-01-02'],
    '제품': ['A', 'B', 'A', 'B'],
    '판매량': [100, 200, 150, 250]
}

df = pd.DataFrame(data)

result = df.pivot(index='날짜', columns='제품', values='판매량')

print(result)

제품            A    B
날짜
2024-01-01  100  200
2024-01-02  150  250

## 피벗 미니퀘스트 2번

In [21]:
import pandas as pd

data = {
    '카테고리': ['전자', '가전', '전자', '가전'],
    '제품': ['A', 'B', 'A', 'B'],
    '판매량': [100, 200, 150, 250]
}

df = pd.DataFrame(data)

result = pd.pivot_table(
    df,
    index='카테고리',
    columns='제품',
    values='판매량',
    aggfunc='sum'
)

print(result)

제품        A      B
카테고리
가전      NaN  450.0
전자    250.0    NaN

## 피벗 미니퀘스트 3번

In [22]:
import pandas as pd

data = {
    '날짜': ['2024-01-01', '2024-01-01', '2024-01-02', '2024-01-02'],
    '제품': ['A', 'B', 'A', 'B'],
    '판매량': [100, 200, 150, 250],
    '이익': [20, 50, 30, 60]
}

df = pd.DataFrame(data)

result = df.pivot(
    index='날짜',
    columns='제품',
    values=['판매량', '이익']
)

print(result)

            판매량       이익
제품            A    B   A   B
날짜
2024-01-01  100  200  20  50
2024-01-02  150  250  30  60

## 중복제거 미니퀘스트 1번

In [23]:
import pandas as pd

data = {
    '이름': ['김철수', '이영희', '김철수', '박민수'],
    '나이': [25, 30, 25, 40],
    '성별': ['남', '여', '남', '남']
}

df = pd.DataFrame(data)

new_df = df.drop_duplicates()

print(new_df)

    이름  나이 성별
0  김철수  25  남
1  이영희  30  여
3  박민수  40  남

## 중복제거 미니퀘스트 2번

In [24]:
import pandas as pd

data = {
    '제품': ['노트북', '태블릿', '노트북', '스마트폰'],
    '가격': [1500000, 800000, 1500000, 1000000],
    '카테고리': ['전자기기', '전자기기', '전자기기', '전자기기']
}

df = pd.DataFrame(data)

new_df = df.drop_duplicates(subset=['제품'])

print(new_df)

print(df.duplicated(subset=['제품']))

     제품       가격  카테고리
0   노트북  1500000  전자기기
1   태블릿   800000  전자기기
3  스마트폰  1000000  전자기기
0    False
1    False
2     True
3    False
dtype: bool

## 중복제거 미니퀘스트 3번

In [26]:
import pandas as pd

data = {
    '학생': ['김민수', '박지현', '김민수', '이정훈'],
    '성적': [90, 85, 90, 88],
    '학교': ['A고', 'B고', 'A고', 'C고']
}

df = pd.DataFrame(data)

new_df = df.drop_duplicates()

print(new_df)

    학생  성적  학교
0  김민수  90  A고
1  박지현  85  B고
3  이정훈  88  C고

## 문자열 처리 미니퀘스트 1번

In [27]:
import pandas as pd

data = pd.Series(["HELLO", "WORLD", "PYTHON", "PANDAS"])

result = data.str.lower()

print(result)

0     hello
1     world
2    python
3    pandas
dtype: str

## 문자열 처리 미니퀘스트 2번

In [28]:
import pandas as pd

df = pd.DataFrame({
    "이름": [" John Doe", "Alice", " Bob", "Charlie Doe"]
})

df["이름"] = df["이름"].str.strip()

result = df[df["이름"].str.contains("Doe")]

print(result)

            이름
0     John Doe
3  Charlie Doe

## 문자열 처리 미니퀘스트 3번

In [29]:
import pandas as pd

df = pd.DataFrame({
    "성명": ["빅데이터 분석", "데이터 과학", "머신 러닝", "딥 러닝"]
})

df["약어"] = df["성명"].str.split().apply(lambda words: ''.join(word[0] for word in words))

print(df)

        성명  약어
0  빅데이터 분석  빅분
1   데이터 과학  데과
2    머신 러닝  머러
3     딥 러닝  딥러

## 추가 과제 1번, 2번 (ai로 데이터 생성 해보기)

In [1]:
import pandas as pd

data = {
    "Date": [
        "2026-05-01", "2026-05-01", "2026-05-01", "2026-05-01", "2026-05-01",
        "2026-05-02", "2026-05-02", "2026-05-02", "2026-05-02", "2026-05-02",
        "2026-05-03", "2026-05-03", "2026-05-03", "2026-05-03", "2026-05-03",
        "2026-05-04", "2026-05-04", "2026-05-04", "2026-05-04", "2026-05-04",
        "2026-05-05", "2026-05-05", "2026-05-05", "2026-05-05", "2026-05-05",
        "2026-05-06", "2026-05-06", "2026-05-06", "2026-05-06", "2026-05-06",
        "2026-05-07", "2026-05-07", "2026-05-07", "2026-05-07", "2026-05-07",
        "2026-05-08", "2026-05-08", "2026-05-08", "2026-05-08", "2026-05-08"
    ],
    "Menu": [
        "Americano", "Latte", "Cappuccino", "Smoothie", "Cake",
        "Americano", "Latte", "Ade", "Sandwich", "Cake",
        "Americano", "Cappuccino", "Smoothie", "Ade", "Cookie",
        "Latte", "Americano", "Sandwich", "Cake", "Smoothie",
        "Americano", "Latte", "Cappuccino", "Cookie", "Ade",
        "Americano", "Smoothie", "Sandwich", "Cake", "Latte",
        "Cappuccino", "Americano", "Ade", "Cookie", "Sandwich",
        "Americano", "Latte", "Smoothie", "Cake", "Cappuccino"
    ],
    "Category": [
        "Coffee", "Coffee", "Coffee", "Beverage", "Dessert",
        "Coffee", "Coffee", "Beverage", "Food", "Dessert",
        "Coffee", "Coffee", "Beverage", "Beverage", "Dessert",
        "Coffee", "Coffee", "Food", "Dessert", "Beverage",
        "Coffee", "Coffee", "Coffee", "Dessert", "Beverage",
        "Coffee", "Beverage", "Food", "Dessert", "Coffee",
        "Coffee", "Coffee", "Beverage", "Dessert", "Food",
        "Coffee", "Coffee", "Beverage", "Dessert", "Coffee"
    ],
    "Price": [
        3000, 4000, 4500, 5500, 6500,
        3000, 4000, 5000, 7000, 6500,
        3000, 4500, 5500, 5000, 3500,
        4000, 3000, 7000, 6500, 5500,
        3000, 4000, 4500, 3500, 5000,
        3000, 5500, 7000, 6500, 4000,
        4500, 3000, 5000, 3500, 7000,
        3000, 4000, 5500, 6500, 4500
    ],
    "Quantity": [
        3, 2, 1, 2, 1,
        4, 3, 2, 1, 2,
        5, 2, 3, 2, 4,
        3, 6, 2, 2, 1,
        7, 4, 2, 5, 3,
        6, 2, 3, 1, 5,
        3, 8, 4, 6, 2,
        9, 5, 3, 2, 4
    ],
    "Payment": [
        "Card", "Card", "Cash", "Card", "Card",
        "Card", "Cash", "Card", "Card", "Cash",
        "Card", "Card", "Cash", "Card", "Card",
        "Cash", "Card", "Card", "Card", "Cash",
        "Card", "Card", "Cash", "Card", "Card",
        "Card", "Cash", "Card", "Card", "Card",
        "Cash", "Card", "Card", "Cash", "Card",
        "Card", "Card", "Cash", "Card", "Card"
    ]
}

df = pd.DataFrame(data)

df["Sales"] = df["Price"] * df["Quantity"]

df

          Date        Menu  Category  Price  Quantity Payment  Sales
0   2026-05-01   Americano    Coffee   3000         3    Card   9000
1   2026-05-01       Latte    Coffee   4000         2    Card   8000
2   2026-05-01  Cappuccino    Coffee   4500         1    Cash   4500
3   2026-05-01    Smoothie  Beverage   5500         2    Card  11000
4   2026-05-01        Cake   Dessert   6500         1    Card   6500
5   2026-05-02   Americano    Coffee   3000         4    Card  12000
6   2026-05-02       Latte    Coffee   4000         3    Cash  12000
7   2026-05-02         Ade  Beverage   5000         2    Card  10000
8   2026-05-02    Sandwich      Food   7000         1    Card   7000
9   2026-05-02        Cake   Dessert   6500         2    Cash  13000
10  2026-05-03   Americano    Coffee   3000         5    Card  15000
11  2026-05-03  Cappuccino    Coffee   4500         2    Card   9000
12  2026-05-03    Smoothie  Beverage   5500         3    Cash  16500
13  2026-05-03         Ade  Beverage   5000         2    Card  10000
14  2026-05-03      Cookie   Dessert   3500         4    Card  14000
15  2026-05-04       Latte    Coffee   4000         3    Cash  12000
16  2026-05-04   Americano    Coffee   3000         6    Card  18000
17  2026-05-04    Sandwich      Food   7000         2    Card  14000
18  2026-05-04        Cake   Dessert   6500         2    Card  13000
19  2026-05-04    Smoothie  Beverage   5500         1    Cash   5500
20  2026-05-05   Americano    Coffee   3000         7    Card  21000
21  2026-05-05       Latte    Coffee   4000         4    Card  16000
22  2026-05-05  Cappuccino    Coffee   4500         2    Cash   9000
23  2026-05-05      Cookie   Dessert   3500         5    Card  17500
24  2026-05-05         Ade  Beverage   5000         3    Card  15000
25  2026-05-06   Americano    Coffee   3000         6    Card  18000
26  2026-05-06    Smoothie  Beverage   5500         2    Cash  11000
27  2026-05-06    Sandwich      Food   7000         3    Card  21000
28  2026-05-06        Cake   Dessert   6500         1    Card   6500
29  2026-05-06       Latte    Coffee   4000         5    Card  20000
30  2026-05-07  Cappuccino    Coffee   4500         3    Cash  13500
31  2026-05-07   Americano    Coffee   3000         8    Card  24000
32  2026-05-07         Ade  Beverage   5000         4    Card  20000
33  2026-05-07      Cookie   Dessert   3500         6    Cash  21000
34  2026-05-07    Sandwich      Food   7000         2    Card  14000
35  2026-05-08   Americano    Coffee   3000         9    Card  27000
36  2026-05-08       Latte    Coffee   4000         5    Card  20000
37  2026-05-08    Smoothie  Beverage   5500         3    Cash  16500
38  2026-05-08        Cake   Dessert   6500         2    Card  13000
39  2026-05-08  Cappuccino    Coffee   4500         4    Card  18000

## 1. 데이터를 pandas DataFrame으로 만들고, groupby 기능을 사용해보세요.

In [2]:
category_summary = df.groupby("Category").agg({
    "Quantity": "sum",
    "Sales": "sum"
})

category_summary

          Quantity   Sales
Category
Beverage        22  115500
Coffee          82  286000
Dessert         23  104500
Food             8   56000

## 2. 데이터를 DataFrame으로 만들고, 특정 조건을 필터링한 DataFrame을 만드세요.

In [3]:
filtered_df = df[(df["Category"] == "Coffee") & (df["Sales"] >= 15000)]

filtered_df

          Date        Menu Category  Price  Quantity Payment  Sales
10  2026-05-03   Americano   Coffee   3000         5    Card  15000
16  2026-05-04   Americano   Coffee   3000         6    Card  18000
20  2026-05-05   Americano   Coffee   3000         7    Card  21000
21  2026-05-05       Latte   Coffee   4000         4    Card  16000
25  2026-05-06   Americano   Coffee   3000         6    Card  18000
29  2026-05-06       Latte   Coffee   4000         5    Card  20000
31  2026-05-07   Americano   Coffee   3000         8    Card  24000
35  2026-05-08   Americano   Coffee   3000         9    Card  27000
36  2026-05-08       Latte   Coffee   4000         5    Card  20000
39  2026-05-08  Cappuccino   Coffee   4500         4    Card  18000